# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form8_vscan.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(333, 184)
        self.pushButton_2 = QPushButton(Form)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(170, 160, 161, 23))
        self.label = QLabel(Form)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(5, 5, 326, 16))
        self.label.setAlignment(Qt.AlignCenter)
        self.pushButton = QPushButton(Form)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(5, 160, 161, 23))
        self.groupBox = QGroupBox(Form)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(5, 20, 161, 71))
        self.lsm__vscan_size__m0 = QTextEdit(self.groupBox)
        self.lsm__vscan_size__m0.setObjectName(u"lsm__vscan_size__m0")
        self.lsm__vscan_size__m0.setGeometry(QRect(65, 20, 91, 20))
        self.lsm__vscan_size__m0.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__vscan_size__m0.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__vscan_size__m0.setReadOnly(True)
        self.lsm__vscan_shift__m0 = QTextEdit(self.groupBox)
        self.lsm__vscan_shift__m0.setObjectName(u"lsm__vscan_shift__m0")
        self.lsm__vscan_shift__m0.setGeometry(QRect(65, 45, 91, 20))
        self.lsm__vscan_shift__m0.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__vscan_shift__m0.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__vscan_shift__m0.setReadOnly(True)
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 20, 56, 16))
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 45, 61, 16))
        self.groupBox_2 = QGroupBox(Form)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(170, 20, 161, 71))
        self.lsm__vscan_size__m1 = QTextEdit(self.groupBox_2)
        self.lsm__vscan_size__m1.setObjectName(u"lsm__vscan_size__m1")
        self.lsm__vscan_size__m1.setGeometry(QRect(65, 20, 91, 20))
        self.lsm__vscan_size__m1.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__vscan_size__m1.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__vscan_size__m1.setReadOnly(True)
        self.lsm__vscan_shift__m1 = QTextEdit(self.groupBox_2)
        self.lsm__vscan_shift__m1.setObjectName(u"lsm__vscan_shift__m1")
        self.lsm__vscan_shift__m1.setGeometry(QRect(65, 45, 91, 20))
        self.lsm__vscan_shift__m1.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__vscan_shift__m1.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__vscan_shift__m1.setReadOnly(True)
        self.label_3 = QLabel(self.groupBox_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 20, 56, 16))
        self.label_7 = QLabel(self.groupBox_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 45, 61, 16))
        self.groupBox_3 = QGroupBox(Form)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(5, 90, 161, 71))
        self.lsm__vscan_size__m2 = QTextEdit(self.groupBox_3)
        self.lsm__vscan_size__m2.setObjectName(u"lsm__vscan_size__m2")
        self.lsm__vscan_size__m2.setGeometry(QRect(65, 20, 91, 20))
        self.lsm__vscan_size__m2.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__vscan_size__m2.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__vscan_size__m2.setReadOnly(True)
        self.lsm__vscan_shift__m2 = QTextEdit(self.groupBox_3)
        self.lsm__vscan_shift__m2.setObjectName(u"lsm__vscan_shift__m2")
        self.lsm__vscan_shift__m2.setGeometry(QRect(65, 45, 91, 20))
        self.lsm__vscan_shift__m2.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__vscan_shift__m2.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__vscan_shift__m2.setReadOnly(True)
        self.label_4 = QLabel(self.groupBox_3)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 20, 56, 16))
        self.label_8 = QLabel(self.groupBox_3)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 45, 61, 16))
        self.groupBox_4 = QGroupBox(Form)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(170, 90, 161, 71))
        self.lsm__vscan_size__m3 = QTextEdit(self.groupBox_4)
        self.lsm__vscan_size__m3.setObjectName(u"lsm__vscan_size__m3")
        self.lsm__vscan_size__m3.setGeometry(QRect(65, 20, 91, 20))
        self.lsm__vscan_size__m3.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__vscan_size__m3.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__vscan_size__m3.setReadOnly(True)
        self.lsm__vscan_shift__m3 = QTextEdit(self.groupBox_4)
        self.lsm__vscan_shift__m3.setObjectName(u"lsm__vscan_shift__m3")
        self.lsm__vscan_shift__m3.setGeometry(QRect(65, 45, 91, 20))
        self.lsm__vscan_shift__m3.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__vscan_shift__m3.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__vscan_shift__m3.setReadOnly(True)
        self.label_5 = QLabel(self.groupBox_4)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 20, 56, 16))
        self.label_9 = QLabel(self.groupBox_4)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 45, 61, 16))

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"\u0412\u0435\u0440\u0442\u0438\u043a\u0430\u043b\u044c\u043d\u0430\u044f \u0440\u0430\u0437\u0432\u0435\u0440\u0442\u043a\u0430", None))
        self.pushButton_2.setText(QCoreApplication.translate("Form", u"\u0423\u0441\u0442\u0430\u043d\u043e\u0432\u0438\u0442\u044c", None))
        self.label.setText(QCoreApplication.translate("Form", u"\u0412\u0435\u0440\u0442\u0438\u043a\u0430\u043b\u044c\u043d\u0430\u044f \u0440\u0430\u0437\u0432\u0435\u0440\u0442\u043a\u0430", None))
        self.pushButton.setText(QCoreApplication.translate("Form", u"\u041e\u0431\u043d\u043e\u0432\u0438\u0442\u044c", None))
        self.groupBox.setTitle(QCoreApplication.translate("Form", u"\u041c\u043e\u0434\u0443\u043b\u044c 1", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"\u0420\u0430\u0437\u043c\u0435\u0440", None))
        self.label_6.setText(QCoreApplication.translate("Form", u"\u0421\u043c\u0435\u0449\u0435\u043d\u0438\u0435", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("Form", u"\u041c\u043e\u0434\u0443\u043b\u044c 1", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"\u0420\u0430\u0437\u043c\u0435\u0440", None))
        self.label_7.setText(QCoreApplication.translate("Form", u"\u0421\u043c\u0435\u0449\u0435\u043d\u0438\u0435", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("Form", u"\u041c\u043e\u0434\u0443\u043b\u044c 1", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"\u0420\u0430\u0437\u043c\u0435\u0440", None))
        self.label_8.setText(QCoreApplication.translate("Form", u"\u0421\u043c\u0435\u0449\u0435\u043d\u0438\u0435", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("Form", u"\u041c\u043e\u0434\u0443\u043b\u044c 1", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"\u0420\u0430\u0437\u043c\u0435\u0440", None))
        self.label_9.setText(QCoreApplication.translate("Form", u"\u0421\u043c\u0435\u0449\u0435\u043d\u0438\u0435", None))
    # retranslateUi

