# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form1roSSeC.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(677, 499)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(677, 499))
        MainWindow.setMaximumSize(QSize(677, 499))
        font = QFont()
        font.setPointSize(8)
        MainWindow.setFont(font)
        MainWindow.setWindowTitle(u"LSM")
        MainWindow.setToolButtonStyle(Qt.ToolButtonIconOnly)
        MainWindow.setDockOptions(QMainWindow.AllowTabbedDocks|QMainWindow.AnimatedDocks)
        self.action_USB = QAction(MainWindow)
        self.action_USB.setObjectName(u"action_USB")
        self.action = QAction(MainWindow)
        self.action.setObjectName(u"action")
        self.action_2 = QAction(MainWindow)
        self.action_2.setObjectName(u"action_2")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.lsm__short_status = QPushButton(self.centralwidget)
        self.lsm__short_status.setObjectName(u"lsm__short_status")
        self.lsm__short_status.setGeometry(QRect(554, 170, 121, 56))
        self.lsm__set_setting = QPushButton(self.centralwidget)
        self.lsm__set_setting.setObjectName(u"lsm__set_setting")
        self.lsm__set_setting.setGeometry(QRect(550, 340, 126, 56))
        self.pushButton_3 = QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(550, 427, 126, 26))
        self.lsm__stop = QPushButton(self.centralwidget)
        self.lsm__stop.setObjectName(u"lsm__stop")
        self.lsm__stop.setGeometry(QRect(120, 405, 75, 23))
        self.lsm__reset = QPushButton(self.centralwidget)
        self.lsm__reset.setObjectName(u"lsm__reset")
        self.lsm__reset.setGeometry(QRect(120, 430, 75, 23))
        self.lsm__start = QPushButton(self.centralwidget)
        self.lsm__start.setObjectName(u"lsm__start")
        self.lsm__start.setGeometry(QRect(305, 405, 75, 23))
        self.lsm__hard_reset = QPushButton(self.centralwidget)
        self.lsm__hard_reset.setObjectName(u"lsm__hard_reset")
        self.lsm__hard_reset.setGeometry(QRect(305, 430, 75, 23))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(45, 405, 56, 16))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(40, 430, 61, 16))
        self.label_2.setFont(font)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(220, 410, 66, 16))
        self.label_3.setWordWrap(True)
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(5, 335, 541, 30))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.frame.setLineWidth(1)
        self.label_5 = QLabel(self.frame)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(15, 5, 91, 16))
        self.spinBox_trigger_complect = QSpinBox(self.frame)
        self.spinBox_trigger_complect.setObjectName(u"spinBox_trigger_complect")
        self.spinBox_trigger_complect.setGeometry(QRect(520, 5, 16, 20))
        self.lsm__lsm_module_0__m0 = QComboBox(self.frame)
        self.lsm__lsm_module_0__m0.setObjectName(u"lsm__lsm_module_0__m0")
        self.lsm__lsm_module_0__m0.setGeometry(QRect(116, 5, 100, 20))
        self.lsm__lsm_module_1__m1 = QComboBox(self.frame)
        self.lsm__lsm_module_1__m1.setObjectName(u"lsm__lsm_module_1__m1")
        self.lsm__lsm_module_1__m1.setGeometry(QRect(220, 5, 100, 20))
        self.lsm__lsm_module_2__m2 = QComboBox(self.frame)
        self.lsm__lsm_module_2__m2.setObjectName(u"lsm__lsm_module_2__m2")
        self.lsm__lsm_module_2__m2.setGeometry(QRect(331, 5, 100, 20))
        self.lsm__lsm_module_3__m3 = QComboBox(self.frame)
        self.lsm__lsm_module_3__m3.setObjectName(u"lsm__lsm_module_3__m3")
        self.lsm__lsm_module_3__m3.setGeometry(QRect(435, 5, 86, 20))
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(265, 310, 131, 25))
        font1 = QFont()
        font1.setPointSize(14)
        font1.setBold(True)
        font1.setWeight(75)
        self.label_6.setFont(font1)
        self.label_6.setAlignment(Qt.AlignCenter)
        self.frame_2 = QFrame(self.centralwidget)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(5, 270, 541, 30))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.frame_2.setLineWidth(1)
        self.lsm__synchronization__m2 = QTextEdit(self.frame_2)
        self.lsm__synchronization__m2.setObjectName(u"lsm__synchronization__m2")
        self.lsm__synchronization__m2.setGeometry(QRect(331, 5, 100, 20))
        self.lsm__synchronization__m2.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__synchronization__m2.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__synchronization__m2.setReadOnly(True)
        self.lsm__synchronization__m0 = QTextEdit(self.frame_2)
        self.lsm__synchronization__m0.setObjectName(u"lsm__synchronization__m0")
        self.lsm__synchronization__m0.setGeometry(QRect(116, 5, 100, 20))
        self.lsm__synchronization__m0.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__synchronization__m0.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__synchronization__m0.setReadOnly(True)
        self.lsm__synchronization__m1 = QTextEdit(self.frame_2)
        self.lsm__synchronization__m1.setObjectName(u"lsm__synchronization__m1")
        self.lsm__synchronization__m1.setGeometry(QRect(220, 5, 100, 20))
        self.lsm__synchronization__m1.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__synchronization__m1.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__synchronization__m1.setReadOnly(True)
        self.label_7 = QLabel(self.frame_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 5, 96, 16))
        self.label_7.setAlignment(Qt.AlignCenter)
        self.lsm__synchronization__m3 = QTextEdit(self.frame_2)
        self.lsm__synchronization__m3.setObjectName(u"lsm__synchronization__m3")
        self.lsm__synchronization__m3.setGeometry(QRect(435, 5, 100, 20))
        self.lsm__synchronization__m3.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__synchronization__m3.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__synchronization__m3.setReadOnly(True)
        self.frame_3 = QFrame(self.centralwidget)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(5, 235, 541, 30))
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.frame_3.setLineWidth(1)
        self.lsm__horizontal_scan__m2 = QTextEdit(self.frame_3)
        self.lsm__horizontal_scan__m2.setObjectName(u"lsm__horizontal_scan__m2")
        self.lsm__horizontal_scan__m2.setGeometry(QRect(331, 5, 100, 20))
        self.lsm__horizontal_scan__m2.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__horizontal_scan__m2.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__horizontal_scan__m2.setReadOnly(True)
        self.lsm__horizontal_scan__m0 = QTextEdit(self.frame_3)
        self.lsm__horizontal_scan__m0.setObjectName(u"lsm__horizontal_scan__m0")
        self.lsm__horizontal_scan__m0.setGeometry(QRect(116, 5, 100, 20))
        self.lsm__horizontal_scan__m0.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__horizontal_scan__m0.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__horizontal_scan__m0.setReadOnly(True)
        self.lsm__horizontal_scan__m1 = QTextEdit(self.frame_3)
        self.lsm__horizontal_scan__m1.setObjectName(u"lsm__horizontal_scan__m1")
        self.lsm__horizontal_scan__m1.setGeometry(QRect(220, 5, 100, 20))
        self.lsm__horizontal_scan__m1.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__horizontal_scan__m1.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__horizontal_scan__m1.setReadOnly(True)
        self.lsm__horizontal_scan__m3 = QTextEdit(self.frame_3)
        self.lsm__horizontal_scan__m3.setObjectName(u"lsm__horizontal_scan__m3")
        self.lsm__horizontal_scan__m3.setGeometry(QRect(435, 5, 100, 20))
        self.lsm__horizontal_scan__m3.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__horizontal_scan__m3.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__horizontal_scan__m3.setReadOnly(True)
        self.label_8 = QLabel(self.frame_3)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 0, 96, 26))
        self.label_8.setAlignment(Qt.AlignCenter)
        self.label_8.setWordWrap(True)
        self.frame_4 = QFrame(self.centralwidget)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(5, 165, 541, 30))
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.frame_4.setLineWidth(1)
        self.lsm__radiation__m2 = QTextEdit(self.frame_4)
        self.lsm__radiation__m2.setObjectName(u"lsm__radiation__m2")
        self.lsm__radiation__m2.setGeometry(QRect(331, 5, 100, 20))
        self.lsm__radiation__m2.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__radiation__m2.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__radiation__m0 = QTextEdit(self.frame_4)
        self.lsm__radiation__m0.setObjectName(u"lsm__radiation__m0")
        self.lsm__radiation__m0.setGeometry(QRect(116, 5, 100, 20))
        self.lsm__radiation__m0.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__radiation__m0.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__radiation__m0.setReadOnly(True)
        self.lsm__radiation__m1 = QTextEdit(self.frame_4)
        self.lsm__radiation__m1.setObjectName(u"lsm__radiation__m1")
        self.lsm__radiation__m1.setGeometry(QRect(220, 5, 100, 20))
        self.lsm__radiation__m1.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__radiation__m1.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__radiation__m1.setReadOnly(True)
        self.label_9 = QLabel(self.frame_4)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 5, 96, 16))
        self.label_9.setAlignment(Qt.AlignCenter)
        self.lsm__radiation__m3 = QTextEdit(self.frame_4)
        self.lsm__radiation__m3.setObjectName(u"lsm__radiation__m3")
        self.lsm__radiation__m3.setGeometry(QRect(435, 5, 100, 20))
        self.lsm__radiation__m3.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__radiation__m3.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__radiation__m3.setReadOnly(True)
        self.frame_5 = QFrame(self.centralwidget)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(5, 200, 541, 30))
        self.frame_5.setInputMethodHints(Qt.ImhNone)
        self.frame_5.setFrameShape(QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.frame_5.setLineWidth(1)
        self.lsm__vertical_scan__m2 = QTextEdit(self.frame_5)
        self.lsm__vertical_scan__m2.setObjectName(u"lsm__vertical_scan__m2")
        self.lsm__vertical_scan__m2.setGeometry(QRect(331, 5, 100, 20))
        self.lsm__vertical_scan__m2.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__vertical_scan__m2.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__vertical_scan__m2.setReadOnly(True)
        self.lsm__vertical_scan__m0 = QTextEdit(self.frame_5)
        self.lsm__vertical_scan__m0.setObjectName(u"lsm__vertical_scan__m0")
        self.lsm__vertical_scan__m0.setGeometry(QRect(116, 5, 100, 20))
        self.lsm__vertical_scan__m0.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__vertical_scan__m0.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__vertical_scan__m0.setReadOnly(True)
        self.lsm__vertical_scan__m1 = QTextEdit(self.frame_5)
        self.lsm__vertical_scan__m1.setObjectName(u"lsm__vertical_scan__m1")
        self.lsm__vertical_scan__m1.setGeometry(QRect(220, 5, 100, 20))
        self.lsm__vertical_scan__m1.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__vertical_scan__m1.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__vertical_scan__m1.setReadOnly(True)
        self.label_10 = QLabel(self.frame_5)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 0, 96, 26))
        self.label_10.setAlignment(Qt.AlignCenter)
        self.label_10.setWordWrap(True)
        self.lsm__vertical_scan__m3 = QTextEdit(self.frame_5)
        self.lsm__vertical_scan__m3.setObjectName(u"lsm__vertical_scan__m3")
        self.lsm__vertical_scan__m3.setGeometry(QRect(434, 6, 100, 20))
        self.lsm__vertical_scan__m3.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__vertical_scan__m3.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__vertical_scan__m3.setReadOnly(True)
        self.frame_6 = QFrame(self.centralwidget)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setGeometry(QRect(5, 370, 541, 30))
        self.frame_6.setFrameShape(QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QFrame.Raised)
        self.frame_6.setLineWidth(1)
        self.label_11 = QLabel(self.frame_6)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 0, 96, 26))
        self.label_11.setAlignment(Qt.AlignCenter)
        self.label_11.setWordWrap(True)
        self.lsm__power = QComboBox(self.frame_6)
        self.lsm__power.addItem("")
        self.lsm__power.setObjectName(u"lsm__power")
        self.lsm__power.setGeometry(QRect(114, 5, 421, 20))
        self.lsm__power.setModelColumn(0)
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(185, 115, 81, 16))
        self.label_12.setAlignment(Qt.AlignCenter)
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(395, 115, 81, 16))
        self.label_13.setAlignment(Qt.AlignCenter)
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(264, 75, 131, 31))
        self.label_14.setFont(font1)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(200, 425, 101, 31))
        self.label_4.setAlignment(Qt.AlignCenter)
        self.frame_7 = QFrame(self.centralwidget)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setGeometry(QRect(5, 130, 541, 31))
        self.frame_7.setFrameShape(QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QFrame.Raised)
        self.frame_7.setLineWidth(1)
        self.lsm__link_mc1 = QTextEdit(self.frame_7)
        self.lsm__link_mc1.setObjectName(u"lsm__link_mc1")
        self.lsm__link_mc1.setGeometry(QRect(220, 5, 100, 20))
        self.lsm__link_mc1.setInputMethodHints(Qt.ImhNone)
        self.lsm__link_mc1.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__link_mc1.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__link_mc1.setReadOnly(True)
        self.label_15 = QLabel(self.frame_7)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 5, 96, 16))
        self.label_15.setAlignment(Qt.AlignCenter)
        self.lsm__link_mc2 = QTextEdit(self.frame_7)
        self.lsm__link_mc2.setObjectName(u"lsm__link_mc2")
        self.lsm__link_mc2.setGeometry(QRect(435, 5, 100, 20))
        self.lsm__link_mc2.setInputMethodHints(Qt.ImhNone)
        self.lsm__link_mc2.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__link_mc2.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__link_mc2.setReadOnly(True)
        self.lsm__link_request_k1 = QPushButton(self.frame_7)
        self.lsm__link_request_k1.setObjectName(u"lsm__link_request_k1")
        self.lsm__link_request_k1.setGeometry(QRect(115, 4, 102, 22))
        self.lsm__link_request_k2 = QPushButton(self.frame_7)
        self.lsm__link_request_k2.setObjectName(u"lsm__link_request_k2")
        self.lsm__link_request_k2.setGeometry(QRect(330, 4, 102, 22))
        self.label_16 = QLabel(self.centralwidget)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(0, 0, 681, 66))
        font2 = QFont()
        font2.setFamily(u"Agency FB")
        font2.setPointSize(8)
        self.label_16.setFont(font2)
        self.label_16.setPixmap(QPixmap(u"../img/lsm_logo.png"))
        self.label_16.setScaledContents(True)
        self.frame_8 = QFrame(self.centralwidget)
        self.frame_8.setObjectName(u"frame_8")
        self.frame_8.setGeometry(QRect(550, 120, 126, 41))
        self.frame_8.setFrameShape(QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QFrame.Raised)
        self.label_17 = QLabel(self.frame_8)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(7, 0, 56, 16))
        self.label_17.setAlignment(Qt.AlignCenter)
        self.label_18 = QLabel(self.frame_8)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(67, 0, 56, 16))
        self.label_18.setAlignment(Qt.AlignCenter)
        self.lsm__date = QTextEdit(self.frame_8)
        self.lsm__date.setObjectName(u"lsm__date")
        self.lsm__date.setGeometry(QRect(5, 20, 59, 20))
        self.lsm__date.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__date.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__date.setReadOnly(True)
        self.lsm__time = QTextEdit(self.frame_8)
        self.lsm__time.setObjectName(u"lsm__time")
        self.lsm__time.setGeometry(QRect(64, 20, 59, 20))
        self.lsm__time.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__time.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__time.setReadOnly(True)
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(10, 395, 666, 16))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.label_19 = QLabel(self.centralwidget)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(555, 240, 120, 56))
        self.label_19.setAutoFillBackground(False)
        self.label_19.setStyleSheet(u"border: 3px solid #a0a0a0;")
        self.label_19.setAlignment(Qt.AlignCenter)
        self.line_2 = QFrame(self.centralwidget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(10, 300, 666, 16))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.line_3 = QFrame(self.centralwidget)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(10, 65, 666, 16))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 677, 19))
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName(u"menu")
        self.menu_2 = QMenu(self.menubar)
        self.menu_2.setObjectName(u"menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menu.addAction(self.action_USB)
        self.menu.addAction(self.action_2)
        self.menu_2.addAction(self.action)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        self.action_USB.setText(QCoreApplication.translate("MainWindow", u"\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438 USB", None))
        self.action.setText(QCoreApplication.translate("MainWindow", u"\u041e \u043f\u0440\u043e\u0433\u0440\u043e\u0430\u043c\u043c\u0435", None))
        self.action_2.setText(QCoreApplication.translate("MainWindow", u"\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438 \u041c\u043e\u0434\u0435\u043c\u0430", None))
        self.lsm__short_status.setText(QCoreApplication.translate("MainWindow", u"\u041e\u0431\u043d\u043e\u0432\u0438\u0442\u044c", None))
        self.lsm__set_setting.setText(QCoreApplication.translate("MainWindow", u"\u0412\u044b\u043f\u043e\u043b\u043d\u0438\u0442\u044c", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"\u0412\u044b\u0445\u043e\u0434", None))
        self.lsm__stop.setText(QCoreApplication.translate("MainWindow", u"\u0412\u044b\u043f\u043e\u043b\u043d\u0438\u0442\u044c", None))
        self.lsm__reset.setText(QCoreApplication.translate("MainWindow", u"\u0412\u044b\u043f\u043e\u043b\u043d\u0438\u0442\u044c", None))
        self.lsm__start.setText(QCoreApplication.translate("MainWindow", u"\u0412\u044b\u043f\u043e\u043b\u043d\u0438\u0442\u044c", None))
        self.lsm__hard_reset.setText(QCoreApplication.translate("MainWindow", u"\u0412\u044b\u043f\u043e\u043b\u043d\u0438\u0442\u044c", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u0421\u0422\u041e\u041f \u041b\u0421\u041c", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u0421\u0431\u0440\u043e\u0441 \u041b\u0421\u041c", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u0421\u0422\u0410\u0420\u0422 \u041b\u0421\u041c", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\u0412\u044b\u0431\u043e\u0440 \u043a\u043e\u043c\u043f\u043b\u0435\u043a\u0442\u0430", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\u0423\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u0438\u0435", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\u0421\u0438\u043d\u0445\u0440\u043e\u043d\u0438\u0437\u0430\u0446\u0438\u044f", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"\u0413\u043e\u0440\u0438\u0437\u043e\u043d\u0442\u0430\u043b\u044c\u043d\u0430\u044f \u0440\u0430\u0437\u0432\u0435\u0440\u0442\u043a\u0430", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"\u0418\u0437\u043b\u0443\u0447\u0435\u043d\u0438\u0435", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"\u0412\u0435\u0440\u0442\u0438\u043a\u0430\u043b\u044c\u043d\u0430\u044f \u0440\u0430\u0437\u0432\u0435\u0440\u0442\u043a\u0430", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"\u0412\u044b\u0431\u043e\u0440 \u043c\u043e\u0449\u043d\u043e\u0441\u0442\u0438 \u0438\u0437\u043b\u0443\u0447\u0435\u043d\u0438\u044f", None))
        self.lsm__power.setItemText(0, QCoreApplication.translate("MainWindow", u"\u041d\u043e\u043c\u0438\u043d\u0430\u043b\u044c\u043d\u0430\u044f \u043c\u043e\u0449\u043d\u043e\u0441\u0442\u044c \u0441 \u0434\u0430\u0442\u0447\u0438\u043a\u043e\u043c \u043e\u0441\u0432\u0435\u0449\u0435\u043d\u043d\u043e\u0441\u0442\u0438", None))

        self.label_12.setText(QCoreApplication.translate("MainWindow", u"\u041b\u0435\u0432\u0430\u044f \u0431\u0430\u0448\u043d\u044f", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"\u041f\u0440\u0430\u0432\u0430\u044f \u0431\u0430\u0448\u043d\u044f", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"\u041d\u0430\u0431\u043b\u044e\u0434\u0435\u043d\u0438\u0435", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u0421\u0431\u0440\u043e\u0441 \u041b\u0421\u041c\n"
"\u0432 \u0437\u0430\u0432. \u043d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"\u0418\u0437\u043b\u0443\u0447\u0435\u043d\u0438\u0435", None))
        self.lsm__link_request_k1.setText(QCoreApplication.translate("MainWindow", u"\u0412\u043a\u043b\u044e\u0447\u0438\u0442\u044c", None))
        self.lsm__link_request_k2.setText(QCoreApplication.translate("MainWindow", u"\u0412\u043a\u043b\u044e\u0447\u0438\u0442\u044c", None))
        self.label_16.setText("")
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"\u0414\u0430\u0442\u0430", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"\u0412\u0440\u0435\u043c\u044f", None))
        self.label_19.setText("")
        self.menu.setTitle(QCoreApplication.translate("MainWindow", u"\u0421\u0438\u0441\u0442\u0435\u043c\u0430", None))
        self.menu_2.setTitle(QCoreApplication.translate("MainWindow", u"\u041e \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u0435", None))
        pass
    # retranslateUi

