# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form3.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(679, 345)
        self.tableView = QTableView(Form)
        self.tableView.setObjectName(u"tableView")
        self.tableView.setGeometry(QRect(5, 155, 671, 186))
        self.frame_3 = QFrame(Form)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(10, 90, 541, 30))
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.frame_3.setLineWidth(1)
        self.textEdit_8 = QTextEdit(self.frame_3)
        self.textEdit_8.setObjectName(u"textEdit_8")
        self.textEdit_8.setGeometry(QRect(331, 5, 100, 20))
        self.textEdit_8.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.textEdit_8.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.textEdit_8.setReadOnly(True)
        self.textEdit_9 = QTextEdit(self.frame_3)
        self.textEdit_9.setObjectName(u"textEdit_9")
        self.textEdit_9.setGeometry(QRect(116, 5, 100, 20))
        self.textEdit_9.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.textEdit_9.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.textEdit_9.setReadOnly(True)
        self.textEdit_10 = QTextEdit(self.frame_3)
        self.textEdit_10.setObjectName(u"textEdit_10")
        self.textEdit_10.setGeometry(QRect(220, 5, 100, 20))
        self.textEdit_10.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.textEdit_10.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.textEdit_10.setReadOnly(True)
        self.textEdit_18 = QTextEdit(self.frame_3)
        self.textEdit_18.setObjectName(u"textEdit_18")
        self.textEdit_18.setGeometry(QRect(435, 5, 100, 20))
        self.textEdit_18.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.textEdit_18.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.textEdit_18.setReadOnly(True)
        self.label_8 = QLabel(self.frame_3)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 0, 96, 26))
        self.label_8.setAlignment(Qt.AlignCenter)
        self.label_8.setWordWrap(True)
        self.frame_4 = QFrame(Form)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(10, 20, 541, 30))
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.frame_4.setLineWidth(1)
        self.textEdit_11 = QTextEdit(self.frame_4)
        self.textEdit_11.setObjectName(u"textEdit_11")
        self.textEdit_11.setGeometry(QRect(331, 5, 100, 20))
        self.textEdit_11.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.textEdit_11.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.textEdit_11.setReadOnly(True)
        self.textEdit_12 = QTextEdit(self.frame_4)
        self.textEdit_12.setObjectName(u"textEdit_12")
        self.textEdit_12.setGeometry(QRect(116, 5, 100, 20))
        self.textEdit_12.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.textEdit_12.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.textEdit_12.setReadOnly(True)
        self.textEdit_13 = QTextEdit(self.frame_4)
        self.textEdit_13.setObjectName(u"textEdit_13")
        self.textEdit_13.setGeometry(QRect(220, 5, 100, 20))
        self.textEdit_13.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.textEdit_13.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.textEdit_13.setReadOnly(True)
        self.label_9 = QLabel(self.frame_4)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 5, 96, 16))
        self.label_9.setAlignment(Qt.AlignCenter)
        self.textEdit_20 = QTextEdit(self.frame_4)
        self.textEdit_20.setObjectName(u"textEdit_20")
        self.textEdit_20.setGeometry(QRect(435, 5, 100, 20))
        self.textEdit_20.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.textEdit_20.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.textEdit_20.setReadOnly(True)
        self.frame_2 = QFrame(Form)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(10, 125, 541, 30))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.frame_2.setLineWidth(1)
        self.textEdit_5 = QTextEdit(self.frame_2)
        self.textEdit_5.setObjectName(u"textEdit_5")
        self.textEdit_5.setGeometry(QRect(331, 5, 100, 20))
        self.textEdit_5.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.textEdit_5.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.textEdit_5.setReadOnly(True)
        self.textEdit_6 = QTextEdit(self.frame_2)
        self.textEdit_6.setObjectName(u"textEdit_6")
        self.textEdit_6.setGeometry(QRect(116, 5, 100, 20))
        self.textEdit_6.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.textEdit_6.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.textEdit_6.setReadOnly(True)
        self.textEdit_7 = QTextEdit(self.frame_2)
        self.textEdit_7.setObjectName(u"textEdit_7")
        self.textEdit_7.setGeometry(QRect(220, 5, 100, 20))
        self.textEdit_7.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.textEdit_7.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.textEdit_7.setReadOnly(True)
        self.label_7 = QLabel(self.frame_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 5, 96, 16))
        self.label_7.setAlignment(Qt.AlignCenter)
        self.textEdit_19 = QTextEdit(self.frame_2)
        self.textEdit_19.setObjectName(u"textEdit_19")
        self.textEdit_19.setGeometry(QRect(435, 5, 100, 20))
        self.textEdit_19.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.textEdit_19.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.textEdit_19.setReadOnly(True)
        self.frame_5 = QFrame(Form)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(10, 55, 541, 30))
        self.frame_5.setFrameShape(QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.frame_5.setLineWidth(1)
        self.textEdit_14 = QTextEdit(self.frame_5)
        self.textEdit_14.setObjectName(u"textEdit_14")
        self.textEdit_14.setGeometry(QRect(331, 5, 100, 20))
        self.textEdit_14.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.textEdit_14.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.textEdit_14.setReadOnly(True)
        self.textEdit_15 = QTextEdit(self.frame_5)
        self.textEdit_15.setObjectName(u"textEdit_15")
        self.textEdit_15.setGeometry(QRect(116, 5, 100, 20))
        self.textEdit_15.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.textEdit_15.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.textEdit_15.setReadOnly(True)
        self.textEdit_16 = QTextEdit(self.frame_5)
        self.textEdit_16.setObjectName(u"textEdit_16")
        self.textEdit_16.setGeometry(QRect(220, 5, 100, 20))
        self.textEdit_16.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.textEdit_16.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.textEdit_16.setReadOnly(True)
        self.label_10 = QLabel(self.frame_5)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 0, 96, 26))
        self.label_10.setAlignment(Qt.AlignCenter)
        self.label_10.setWordWrap(True)
        self.textEdit_17 = QTextEdit(self.frame_5)
        self.textEdit_17.setObjectName(u"textEdit_17")
        self.textEdit_17.setGeometry(QRect(435, 5, 100, 20))
        self.textEdit_17.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.textEdit_17.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.textEdit_17.setReadOnly(True)
        self.spinBox = QSpinBox(Form)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setGeometry(QRect(550, 95, 126, 56))
        font = QFont()
        font.setPointSize(12)
        self.spinBox.setFont(font)
        self.spinBox.setAlignment(Qt.AlignCenter)

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"\u0421\u043f\u0438\u0441\u043e\u043a \u0441\u043e\u0431\u044b\u0442\u0438\u0439", None))
        self.label_8.setText(QCoreApplication.translate("Form", u"\u0413\u043e\u0440\u0438\u0437\u043e\u043d\u0442\u0430\u043b\u044c\u043d\u0430\u044f \u0440\u0430\u0437\u0432\u0435\u0440\u0442\u043a\u0430", None))
        self.label_9.setText(QCoreApplication.translate("Form", u"\u0418\u0437\u043b\u0443\u0447\u0435\u043d\u0438\u0435", None))
        self.label_7.setText(QCoreApplication.translate("Form", u"\u0421\u0438\u043d\u0445\u0440\u043e\u043d\u0438\u0437\u0430\u0446\u0438\u044f", None))
        self.label_10.setText(QCoreApplication.translate("Form", u"\u0412\u0435\u0440\u0442\u0438\u043a\u0430\u043b\u044c\u043d\u0430\u044f \u0440\u0430\u0437\u0432\u0435\u0440\u0442\u043a\u0430", None))
    # retranslateUi

