# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form3KpNnoS.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(679, 345)
        self.tableView = QTableView(Form)
        self.tableView.setObjectName(u"tableView")
        self.tableView.setGeometry(QRect(5, 155, 671, 186))
        self.frame_3 = QFrame(Form)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(10, 90, 541, 30))
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.frame_3.setLineWidth(1)
        self.lsm__horizontal_scan__m2__h = QTextEdit(self.frame_3)
        self.lsm__horizontal_scan__m2__h.setObjectName(u"lsm__horizontal_scan__m2__h")
        self.lsm__horizontal_scan__m2__h.setGeometry(QRect(331, 5, 100, 20))
        self.lsm__horizontal_scan__m2__h.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__horizontal_scan__m2__h.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__horizontal_scan__m2__h.setReadOnly(True)
        self.lsm__horizontal_scan__m0__h = QTextEdit(self.frame_3)
        self.lsm__horizontal_scan__m0__h.setObjectName(u"lsm__horizontal_scan__m0__h")
        self.lsm__horizontal_scan__m0__h.setGeometry(QRect(116, 5, 100, 20))
        self.lsm__horizontal_scan__m0__h.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__horizontal_scan__m0__h.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__horizontal_scan__m0__h.setReadOnly(True)
        self.lsm__horizontal_scan__m1__h = QTextEdit(self.frame_3)
        self.lsm__horizontal_scan__m1__h.setObjectName(u"lsm__horizontal_scan__m1__h")
        self.lsm__horizontal_scan__m1__h.setGeometry(QRect(220, 5, 100, 20))
        self.lsm__horizontal_scan__m1__h.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__horizontal_scan__m1__h.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__horizontal_scan__m1__h.setReadOnly(True)
        self.lsm__horizontal_scan__m3__h = QTextEdit(self.frame_3)
        self.lsm__horizontal_scan__m3__h.setObjectName(u"lsm__horizontal_scan__m3__h")
        self.lsm__horizontal_scan__m3__h.setGeometry(QRect(435, 5, 100, 20))
        self.lsm__horizontal_scan__m3__h.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__horizontal_scan__m3__h.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__horizontal_scan__m3__h.setReadOnly(True)
        self.label_8 = QLabel(self.frame_3)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 0, 96, 26))
        self.label_8.setAlignment(Qt.AlignCenter)
        self.label_8.setWordWrap(True)
        self.frame_4 = QFrame(Form)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(10, 20, 541, 30))
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.frame_4.setLineWidth(1)
        self.lsm__radiation__m2__h = QTextEdit(self.frame_4)
        self.lsm__radiation__m2__h.setObjectName(u"lsm__radiation__m2__h")
        self.lsm__radiation__m2__h.setGeometry(QRect(331, 5, 100, 20))
        self.lsm__radiation__m2__h.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__radiation__m2__h.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__radiation__m2__h.setReadOnly(True)
        self.lsm__radiation__m0__h = QTextEdit(self.frame_4)
        self.lsm__radiation__m0__h.setObjectName(u"lsm__radiation__m0__h")
        self.lsm__radiation__m0__h.setGeometry(QRect(116, 5, 100, 20))
        self.lsm__radiation__m0__h.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__radiation__m0__h.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__radiation__m0__h.setReadOnly(True)
        self.lsm__radiation__m1__h = QTextEdit(self.frame_4)
        self.lsm__radiation__m1__h.setObjectName(u"lsm__radiation__m1__h")
        self.lsm__radiation__m1__h.setGeometry(QRect(220, 5, 100, 20))
        self.lsm__radiation__m1__h.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__radiation__m1__h.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__radiation__m1__h.setReadOnly(True)
        self.label_9 = QLabel(self.frame_4)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 5, 96, 16))
        self.label_9.setAlignment(Qt.AlignCenter)
        self.lsm__radiation__m3__h = QTextEdit(self.frame_4)
        self.lsm__radiation__m3__h.setObjectName(u"lsm__radiation__m3__h")
        self.lsm__radiation__m3__h.setGeometry(QRect(435, 5, 100, 20))
        self.lsm__radiation__m3__h.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__radiation__m3__h.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__radiation__m3__h.setReadOnly(True)
        self.frame_2 = QFrame(Form)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(10, 125, 541, 30))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.frame_2.setLineWidth(1)
        self.lsm__sinchronization__m2__h = QTextEdit(self.frame_2)
        self.lsm__sinchronization__m2__h.setObjectName(u"lsm__sinchronization__m2__h")
        self.lsm__sinchronization__m2__h.setGeometry(QRect(331, 5, 100, 20))
        self.lsm__sinchronization__m2__h.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__sinchronization__m2__h.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__sinchronization__m2__h.setReadOnly(True)
        self.lsm__sinchronization__m0__h = QTextEdit(self.frame_2)
        self.lsm__sinchronization__m0__h.setObjectName(u"lsm__sinchronization__m0__h")
        self.lsm__sinchronization__m0__h.setGeometry(QRect(116, 5, 100, 20))
        self.lsm__sinchronization__m0__h.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__sinchronization__m0__h.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__sinchronization__m0__h.setReadOnly(True)
        self.lsm__sinchronization__m1__h = QTextEdit(self.frame_2)
        self.lsm__sinchronization__m1__h.setObjectName(u"lsm__sinchronization__m1__h")
        self.lsm__sinchronization__m1__h.setGeometry(QRect(220, 5, 100, 20))
        self.lsm__sinchronization__m1__h.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__sinchronization__m1__h.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__sinchronization__m1__h.setReadOnly(True)
        self.label_7 = QLabel(self.frame_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 5, 96, 16))
        self.label_7.setAlignment(Qt.AlignCenter)
        self.lsm__sinchronization__m3__h = QTextEdit(self.frame_2)
        self.lsm__sinchronization__m3__h.setObjectName(u"lsm__sinchronization__m3__h")
        self.lsm__sinchronization__m3__h.setGeometry(QRect(435, 5, 100, 20))
        self.lsm__sinchronization__m3__h.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__sinchronization__m3__h.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__sinchronization__m3__h.setReadOnly(True)
        self.frame_5 = QFrame(Form)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(10, 55, 541, 30))
        self.frame_5.setFrameShape(QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.frame_5.setLineWidth(1)
        self.lsm__vertical_scan__m2__h = QTextEdit(self.frame_5)
        self.lsm__vertical_scan__m2__h.setObjectName(u"lsm__vertical_scan__m2__h")
        self.lsm__vertical_scan__m2__h.setGeometry(QRect(331, 5, 100, 20))
        self.lsm__vertical_scan__m2__h.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__vertical_scan__m2__h.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__vertical_scan__m2__h.setReadOnly(True)
        self.lsm__vertical_scan__m0__h = QTextEdit(self.frame_5)
        self.lsm__vertical_scan__m0__h.setObjectName(u"lsm__vertical_scan__m0__h")
        self.lsm__vertical_scan__m0__h.setGeometry(QRect(116, 5, 100, 20))
        self.lsm__vertical_scan__m0__h.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__vertical_scan__m0__h.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__vertical_scan__m0__h.setReadOnly(True)
        self.lsm__vertical_scan__m1__h = QTextEdit(self.frame_5)
        self.lsm__vertical_scan__m1__h.setObjectName(u"lsm__vertical_scan__m1__h")
        self.lsm__vertical_scan__m1__h.setGeometry(QRect(220, 5, 100, 20))
        self.lsm__vertical_scan__m1__h.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__vertical_scan__m1__h.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__vertical_scan__m1__h.setReadOnly(True)
        self.label_10 = QLabel(self.frame_5)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 0, 96, 26))
        self.label_10.setAlignment(Qt.AlignCenter)
        self.label_10.setWordWrap(True)
        self.lsm__vertical_scan__m3 = QTextEdit(self.frame_5)
        self.lsm__vertical_scan__m3.setObjectName(u"lsm__vertical_scan__m3")
        self.lsm__vertical_scan__m3.setGeometry(QRect(435, 5, 100, 20))
        self.lsm__vertical_scan__m3.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__vertical_scan__m3.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.lsm__vertical_scan__m3.setReadOnly(True)
        self.lsm__event_number = QSpinBox(Form)
        self.lsm__event_number.setObjectName(u"lsm__event_number")
        self.lsm__event_number.setGeometry(QRect(550, 95, 126, 56))
        font = QFont()
        font.setPointSize(12)
        self.lsm__event_number.setFont(font)
        self.lsm__event_number.setAlignment(Qt.AlignCenter)

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"\u0421\u043f\u0438\u0441\u043e\u043a \u0441\u043e\u0431\u044b\u0442\u0438\u0439", None))
        self.label_8.setText(QCoreApplication.translate("Form", u"\u0413\u043e\u0440\u0438\u0437\u043e\u043d\u0442\u0430\u043b\u044c\u043d\u0430\u044f \u0440\u0430\u0437\u0432\u0435\u0440\u0442\u043a\u0430", None))
        self.label_9.setText(QCoreApplication.translate("Form", u"\u0418\u0437\u043b\u0443\u0447\u0435\u043d\u0438\u0435", None))
        self.label_7.setText(QCoreApplication.translate("Form", u"\u0421\u0438\u043d\u0445\u0440\u043e\u043d\u0438\u0437\u0430\u0446\u0438\u044f", None))
        self.label_10.setText(QCoreApplication.translate("Form", u"\u0412\u0435\u0440\u0442\u0438\u043a\u0430\u043b\u044c\u043d\u0430\u044f \u0440\u0430\u0437\u0432\u0435\u0440\u0442\u043a\u0430", None))
    # retranslateUi

