commands:
  - name: 'ATD'
    desc: 'Проверка связи с модемом'
    request:
      command: ''
      address: False
      data: 
        values: 
          - type: 'str'
            values: 
              - '41'
          - type: 'str'
            values: 
              - '54'
          - type: 'str'
            values: 
              - '44'
          - type: 'str'
            values:
              - '0d'
      crc: False
    response:
      command: ''
      address: False
      data:
        values:
          - type: 'str'
            values:
              - '0d'
          - type: 'str'
            values: 
              - '0a'
          - type: 'str'
            values:  
              - '4f'
          - type: 'str'
            values:  
              - '4b'
          - type: 'str'
            values:  
              - '0d' 
          - type: 'str'
            values:  
              - '0a'
      crc: False      
    timeout: 1
  - name: 'link_request'
    desc: 'Запрос канала связи'
    request:
      command: '00'
      address: True
      data: 
        values: []
      crc: True
    response:
      command: '80'
      address: True
      data: 
        values: []
      crc: True
    timeout: 1
  - name: 'short_status'
    desc: 'Запрос текущего краткого состояния ЛСМ'
    request:
      command: '01'
      address: True
      data: 
        values: []
      crc: True
    response:
      command: '81'
      address: True
      data: 
        values: 
          - type: 'event_number'
            values:
              - 'high'
          - type: 'event_number'
            values:
              - 'low'
          - type: 'date'
            values:
              - 'year'
          - type: 'date'
            values:
              - 'month'
          - type: 'date'
            values:
              - 'number'
          - type: 'date'
            values:
              - 'weeks_day'
          - type: 'time'
            values:
              - 'hour'
          - type: 'time'
            values:
              - 'min'
          - type: 'time'
            values: 
              - 'sec'
          - type: 'mode'
            values: 
              - 'lsm_module__m0'
              - 'lsm_module__m1'
              - 'lsm_module__m2'
              - 'lsm_module__m2'
              - 'fotoavtomat'
              - 'dynamic_power'
              - 'max_nom_power'
              - 'current_illumination'
          - type: 'state_module'
            values:
              - 'radiation__m0'
              - 'vertical_scan__m0'
              - 'horizontal_scan__m0'
              - 'synchronization__m0'
          - type: 'state_module'
            values:
              - 'radiation__m1'
              - 'vertical_scan__m1'
              - 'horizontal_scan__m1'
              - 'synchronization__m1'
          - type: 'state_module__m2'
            values:
              - 'radiation__m2'
              - 'vertical_scan__m2'
              - 'horizontal_scan__m2'
              - 'synchronization__m2'
          - type: 'state_module'
            values:
              - 'radiation__m3'
              - 'vertical_scan__m3'
              - 'horizontal_scan__m3'
              - 'synchronization__m3'
      crc: True
    timeout: 1  
  - name: 'general_status'
    desc: 'Запрос текущего общего состояния ЛСМ'
    request:
      command: '02'
      address: True
      data: 
        values: []
      crc: True
    response:
      command: '82'
      address: True
      data: 
        values: 
          - type: 'event_number'
            values:
              - 'high'
          - type: 'event_number'
            values:
              - 'low'
          - type: 'date'
            values:
              - 'year'
          - type: 'date'
            values:
              - 'month'
          - type: 'date'
            values:
              - 'number'
          - type: 'date'
            values:
              - 'weeks_day'
          - type: 'time'
            values:
              - 'hour'
          - type: 'time'
            values:
              - 'min'
          - type: 'time'
            values: 
              - 'sec'
          - type: 'mode'
            values: 
              - 'lsm_module__m0'
              - 'lsm_module__m1'
              - 'lsm_module__m2'
              - 'lsm_module__m3'
              - 'fotoavtomat'
              - 'dynamic_power'
              - 'max_nom_power'
              - 'current_illumination'
          - type: 'state_module'
            values:
              - 'radiation__m0'
              - 'vertical_scan__m0'
              - 'horizontal_scan__m0'
              - 'synchronization__m0'
          - type: 'state_module'
            values:
              - 'radiation__m1'
              - 'vertical_scan__m1'
              - 'horizontal_scan__m1'
              - 'synchronization__m1'
          - type: 'state_module__m2'
            values:
              - 'radiation__m2'
              - 'vertical_scan__m2'
              - 'horizontal_scan__m2'
              - 'synchronization__m2'
          - type: 'state_module'
            values:
              - 'radiation__m3'
              - 'vertical_scan__m3'
              - 'horizontal_scan__m3'
              - 'synchronization__m3'
          - type: 'temperature_module'
            values:
              - 'temperature__m0'
          - type: 'temperature_module'
            values:
              - 'temperature__m1' 
          - type: 'temperature_module'
            values:
              - 'temperature__m2'
          - type: 'temperature_module'
            values:
              - 'temperature__m3'
          - type: 'power_module'
            values:
              - 'cur_power__m0'
          - type: 'power_module'
            values:
              - 'cur_power__m1'
          - type: 'power_module'
            values:
              - 'cur_power__m2'
          - type: 'power_module'
            values:
              - 'cur_power__m3'
      crc: True
    timeout: 1  
  - name: 'full_status'
    desc: 'Запрос текущего полного состояния ЛСМ '
    request:
      command: '03'
      address: True
      data: 
        values: []
      crc: True
    response:
      command: '83'
      address: True
      data: 
        values: 
          - type: 'event_number'
            values:
              - 'high'
          - type: 'event_number'
            values:
              - 'low'
          - type: 'date'
            values:
              - 'year'
          - type: 'date'
            values:
              - 'month'
          - type: 'date'
            values:
              - 'number'
          - type: 'date'
            values:
              - 'weeks_day'
          - type: 'time'
            values:
              - 'hour'
          - type: 'time'
            values:
              - 'min'
          - type: 'time'
            values: 
              - 'sec'
          - type: 'mode'
            values: 
              - 'lsm_module__m0'
              - 'lsm_module__m1'
              - 'lsm_module__m2'
              - 'lsm_module__m3'
              - 'fotoavtomat'
              - 'dynamic_power'
              - 'max_nom_power'
              - 'current_illumination'
          - type: 'state_module'
            values:
              - 'radiation__m0'
              - 'vertical_scan__m0'
              - 'horizontal_scan__m0'
              - 'synchronization__m0'
          - type: 'state_module'
            values:
              - 'radiation__m1'
              - 'vertical_scan__m1'
              - 'horizontal_scan__m1'
              - 'synchronization__m1'
          - type: 'state_module'
            values:
              - 'radiation__m2'
              - 'vertical_scan__m2'
              - 'horizontal_scan__m2'
              - 'synchronization__m2'
          - type: 'state_module'
            values:
              - 'radiation__m3'
              - 'vertical_scan__m3'
              - 'horizontal_scan__m3'
              - 'synchronization__m3'
          - type: 'temperature_module'
            values:
              - 'temperature__m0'
          - type: 'temperature_module'
            values:
              - 'temperature__m1' 
          - type: 'temperature_module'
            values:
              - 'temperature__m2'
          - type: 'temperature_module'
            values:
              - 'temperature__m3'
          - type: 'power_module'
            values:
              - 'cur_power__m0'
          - type: 'power_module'
            values:
              - 'cur_power__m1'
          - type: 'power_module'
            values:
              - 'cur_power__m2'
          - type: 'power_module'
            values:
              - 'cur_power__m3'
          - type: 'U'
            values:
              - 'U_1'
          - type: 'U'
            values:
              - 'U_2'
          - type: 'I'
            values:
              - 'I_1'
          - type: 'I'
            values:
              - 'I_2'
          - type: 'T_hull'
            values:
              - 'temperature_hull__k1'
          - type: 'T_hull'
            values:
              - 'temperature_hull__k2'
          - type: 'T_ODT'
            values:
              - 'temperature_odt__k1'
          - type: 'T_ODT__k2'
            values:
              - 'temperature_odt__k2'
          - type: 'Heating__k1'
            values:
              - heating_windows_bottom
              - heating_windows_top
              - heating_lm
              - heating_air
              - peltier_minus_1
              - peltier_plus_1
              - peltier_minus_2
              - peltier_plus_2
          - type: 'Heating__k2'
            values:
              - heating_windows_bottom
              - heating_windows_top
              - heating_lm
              - heating_air
              - peltier_minus_1
              - peltier_plus_1
              - peltier_minus_2
              - peltier_plus_2
          - type: 'cooling__k1'
            values:
              - 'cooler'
          - type: 'cooling__c2'
            values:
              - 'cooler'
      crc: True
    timeout: 1  
  - name: 'set_setting'
    desc: 'Команда установки режима работы ЛСМ'
    request:
      command: '04'
      address: True
      data: 
        values: 
          - type: 'mode'
            values: 
              - 'lsm_module__m0'
              - 'lsm_module__m1'
              - 'lsm_module__m2'
              - 'lsm_module__m3'
              - 'fotoavtomat'
              - 'dynamic_power'
              - 'max_nom_power'
              - 'current_illumination'
      crc: True  
    response:
      command: '84'
      address: True
      data: 
        values:
          - type: 'mode'
            values: 
              - 'lsm_module__m0'
              - 'lsm_module__m1'
              - 'lsm_module__m2'
              - 'lsm_module__m3'
              - 'fotoavtomat'
              - 'dynamic_power'
              - 'max_nom_power'
              - 'current_illumination'
      crc: True
    timeout: 1  
  - name: 'reset_setting'
    desc: 'Команда перезагрузки ЛСМ'
    request:
      command: '05'
      address: True
      data: 
        values: []
      crc: True
    response:
      command: '85'
      address: True
      data: 
        values: []
      crc: True
    timeout: 1
  - name: 'set_modem_setting'
    desc: 'Команда настройки модема'
    request:
      command: '20'
      address: True
      data: 
        values:
          - type: 'modem_setting'
            values:
              - 'SW'
          - type: 'modem_setting'
            values:
              - 'BW'
          - type: 'modem_setting'
            values:
              - 'P'
          - type: 'modem_setting'
            values: 
              - 'CH' 
      crc: True
    response:
      command: 'A0'
      address: True
      data: 
        values: 
          - type: 'modem_setting'
            values:
              - 'SW'
          - type: 'modem_setting'
            values:
              - 'BW'
          - type: 'modem_setting'
            values: 
              - 'P'
          - type: 'modem_setting'
            values: 
              - 'CH'
      crc: True    
    timeout: 1
  - name: 'save_modem_setting'
    desc: 'Команда сохранение настроек модема'
    request:
      command: '21'
      address: True
      data: 
        values: []
      crc: True
    response:
      command: 'a1'
      address: True
      data: 
        values:
          - type: 'modem_setting'
            values: 
              - 'SW'
          - type: 'modem_setting'
            values:
              - 'BW'
          - type: 'modem_setting'
            values:
              - 'P'
          - type: 'modem_setting'
            values:
              - 'CH'
      crc: True     
    timeout: 1
  - name: 'set_factory_setting'
    desc: 'Команда сброса ЛСМ в заводские настройки'
    request:
      command: '06'
      address: True
      data: 
        values: []
      crc: True
    response:
      command: '86'
      address: True
      data: 
        values: []
      crc: True
    timeout: 1
  - name: 'stop'
    desc: 'Команда остановки ЛСМ («СТОП ЛСМ»)'
    request:
      command: '07'
      address: True
      data: 
        values: []
      crc: True
    response:
      command: '87'
      address: True
      data: 
        values: []
      crc: True
    timeout: 1
  - name: 'start'
    desc: 'Команда пуска ЛСМ («ПУСК ЛСМ»)'
    request:
      command: '08'
      address: True
      data: 
        values: []
      crc: True
    response:
      command: '88'
      address: True
      data: 
        values: []
      crc: True
    timeout: 1
  - name: 'save_setting'
    desc: 'Сохранение текущих настроек ЛСМ'
    request:
      command: '09'
      address: True
      data: 
        values: []
      crc: True
    response:
      command: '89'
      address: True
      data: 
        values: []
      crc: True
    timeout: 1
  - name: 'current_time'
    desc: 'Запрос текущего времени'
    request:
      command: '0a'
      address: True
      data: 
        values: []
      crc: True
    response:
      command: '8a'
      address: True
      data: 
        values: 
          - type: 'date'
            values:
              - 'year'
          - type: 'date'
            values:
              - 'month'
          - type: 'date'
            values:
              - 'number'
          - type: 'date'
            values:
              - 'weeks_day'
          - type: 'time'
            values:
              - 'hour'
          - type: 'time'
            values:
              - 'min'
          - type: 'time'
            values: 
              - 'sec'
      crc: True
    timeout: 1
  - name: 'set_time'
    desc: 'Команда установки времени'
    request:
      command: '0b'
      address: True
      data: 
        values:
          - type: 'date'
            values:
              - 'year'
          - type: 'date'
            values:
              - 'month'
          - type: 'date'
            values:
              - 'number'
          - type: 'date'
            values:
              - 'weeks_day'
          - type: 'time'
            values:
              - 'hour'
          - type: 'time'
            values:
              - 'min'
          - type: 'time'
            values: 
              - 'sec'
      crc: True
    response:
      command: '8b'
      address: True
      data: 
        values:
          - type: 'date'
            values:
              - 'year'
          - type: 'date'
            values:
              - 'month'
          - type: 'date'
            values:
              - 'number'
          - type: 'date'
            values:
              - 'weeks_day'
          - type: 'time'
            values:
              - 'hour'
          - type: 'time'
            values:
              - 'min'
          - type: 'time'
            values: 
              - 'sec'
      crc: True
    timeout: 1
  - name: 'last_event'
    desc: 'Запрос номера последнего события'
    request:
      command: '0c'
      address: True
      data: 
        values: []
      crc: True
    response:
      command: '8c'
      address: True
      data: 
        values: []
      crc: True
    timeout: 1
  - name: 'number_event'
    desc: 'Запрос данных из памяти событий'
    request:
      command: '0d'
      address: True
      data: 
        values:
          - type: 'event_number'
            values:
              - 'high'
          - type: 'event_number'
            values:
              - 'low'
      crc: True
    response:
      command: '8d'
      address: True
      data: 
        values: []
      crc: True
    timeout: 1
  - name: 'delete_event_memory'
    desc: 'Стирание данных из памяти событий'
    request:
      command: '0e'
      address: True
      data: 
        values: []
      crc: True
    response:
      command: '8e'
      address: True
      data: 
        values: []
      crc: True
    timeout: 1
  - name: 'address_book'
    desc: 'Запрос адресной книги'
    request:
      command: '0f'
      address: True
      data: 
        values: []
      crc: True
    response:
      command: '8f'
      address: True
      data: 
        values: []
      crc: True
    timeout: 1
  - name: 'write_to_address_book'
    desc: 'Команда записи в адресную книгу'
    request:
      command: '10'
      address: True
      data: 
        values: []
      crc: True
    response:
      command: '90'
      address: True
      data: 
        values: []
      crc: True
    timeout: 1
  - name: 'get_max_power'
    desc: 'Запрос текущей максимальной мощности'
    request:
      command: '11'
      address: True
      data: 
        values: []
      crc: True
    response:
      command: '91'
      address: True
      data: 
        values: []
      crc: True
    timeout: 1
  - name: 'set_max_power'
    desc: 'Команда установки максимальной мощности'
    request:
      command: '12'
      address: True
      data: 
        values: []
      crc: True
    response:
      command: '92'
      address: True
      data: 
        values: []
      crc: True
    timeout: 1
  - name: 'vertical_correction_request'
    desc: 'Запрос коррекции вертикальной развертки'
    request:
      command: '13'
      address: True
      data: 
        values: []
      crc: True
    response:
      command: '93'
      address: True
      data: 
        values: []
      crc: True
    timeout: 1
  - name: 'set_vertical_correction'
    desc: 'Команда коррекции вертикальной развертки'
    request:
      command: '14'
      address: True
      data: 
        values: []
      crc: True
    response:
      command: '94'
      address: True
      data: 
        values: []
      crc: True
    timeout: 1
  - name: 'horizontal_correction_request'
    desc: 'Запрос коррекции горизонтальной развертки'
    request:
      command: '15'
      address: True
      data: 
        values: []
      crc: True
    response:
      command: '95'
      address: True
      data: 
        values: []
      crc: True
    timeout: 1
  - name: 'set_horizontal_correction'
    desc: 'Команда коррекции горизонтальной развертки'
    request:
      command: '16'
      address: True
      data: 
        values: []
      crc: True
    response:
      command: '96'
      address: True
      data: 
        values: []
      crc: True
    timeout: 1
  - name: 'test'
    desc: 'Команда включения тестового режима («ТЕСТ»)'
    request:
      command: '17'
      address: True
      data: 
        values: []
      crc: True
    response:
      command: '97'
      address: True
      data: 
        values: []
      crc: True
    timeout: 1
  - name:  'event_of_change'
    desc: 'Сообщение об изменении состояния и режима'
    request:
      command: '18'
      address: True
      data: 
        values: []
      crc: True
    response:
      command: '98'
      address: True
      data: 
        values: []
      crc: True
    timeout: 1