setting_modem:
  - name: 'SF'
    type: 'list'
    param:
      keys: ['7', '8', '9', '10', '11', '12']
      values: [7, 8, 9, 10, 11, 12]
  - name: 'BW' 
    type: 'list'
    param:
      keys: ['31.25 кГц', '41.70 кГц', '62.5 кГц','125 кГц']
      values: [4, 5, 6, 7]
  - name: 'P'
    type: 'list' 
    param:
      keys: ['2 мВт', '10 мВт', '50 мВт']
      values: [2, 10, 17]
  - name: CH
    type: 'step list'
    param:
      keys:
        start: 433.125
        end: 434.875
        step: 0.125
        name: 'МГц'
      values:
        start: 1
        end: 15
        step: 1
  - name: 'usb_speed'
    type: 'list'
    param:
      keys: [115200]
      values: [115200]
  - name: 'lsm_module_0__m0'
    type: 'list'
    param:
      keys: ['Основной', 'Резервный']
      values: [1,0]
  - name: 'lsm_module_1__m1'
    type: 'list'
    param:
      keys: ['Основной', 'Резервный']
      values: [1,0]
  - name: 'lsm_module_2__m2'
    type: 'list'
    param:
      keys: ['Основной', 'Резервный']
      values: [1,0]
  - name: 'lsm_module_3__m3'
    type: 'list'
    param:
      keys: ['Основной', 'Резервный']
      values: [1,0]
  - name: 'power'
    type: 'list'
    param:
      keys: ['Номинальная мощность с датчиком освещенности', 'Максимальная мощность', 'Динамическое управление мощностью', 'Фотоавтомат']
      values: [0b00001000, 0b00000010, 0b00000100, 0b00000001]

# Параметр:
# name - имя параметра и имя параметра в интерфейсе
# len  - длина параметра
#   values - список описаний каждого байта параметра
#     name - имя элемента
#     type - тип элемента   
#     number - номер первого байта
#     len_param - длина параметра  в байтах 
#     params - список параметров доставаемый из этого байта
#     name - имя подпараметра
#     mask - маска для получения части
#     shift - смещение для получения результата
#     mul  - множитель для получения результата 
#
#

params:
  - name: modem_setting
    type: 'value'
    len: 4
    values:
      - name: 'SW'
        type: 'bit_value'
        number: 0
        len_param: 1
        desc: ''
        mask: 0b11111111
        shift: 0
        mul: 1
      - name: 'BW'
        type: 'bit_value'
        number: 1
        len_param: 1
        desc: ''
        mask: 0b11111111
        shift: 0
        mul: 1 
      - name: 'P'
        type: 'bit_value'
        number: 2
        len_param: 1
        desc: ''
        mask: 0b11111111
        shift: 0
        mul: 1
      - name: 'CH'
        type: 'bit_value'
        number: 3
        len_param: 1
        desc: ''
        mask: 0b11111111
        shift: 0
        mul: 1       
  - name: 'event_number'
    type: 'value_sum'
    len: 2
    values:
      - name: 'high'
        type: 'bit_value'
        number: 0
        len_param: 1
        desc: 'старший байт номера события'
        mask: 0b11111111
        shift: 0
        mul: 1
      - name: 'low'
        type: 'bit_value'
        number: 1
        len_param: 1
        desc: 'младший байт номера события'
        mask: 0b11111111
        shift: 0
        mul: 1
  - name: 'date'
    type: 'value_date'
    len: 3
    values:
      - name: 'year'
        type: 'bit_value'
        number: 0
        len_param: 1
        desc: 'год'
        mask: 0b11111111
        shift: 0
        mul: 1
      - name: 'month'
        type: 'bit_value'
        number: 1
        len_param: 1
        desc: 'месяц'
        mask: 0b11111111
        shift: 0
        mul: 1
      - name: 'number'
        type: 'bit_value'
        number: 2
        len_param: 1
        desc: 'число'
        mask: 0b11111111
        shift: 0
        mul: 1
      - name: 'weeks_day'
        type: 'bit_value'
        number: 3
        len_param: 1
        desc: 'день недели'
        mask: 0b00000111
        shift: 0
        mul: 1
  - name: 'time'
    type: 'value_time'
    len: 3
    values:
      - name: 'hour'
        type: 'bit_value'
        number: 0
        len_param: 1
        desc: 'час'
        mask: 0b11111111
        shift: 0
        mul: 1
      - name: 'min'
        type: 'bit_value'
        number: 1
        len_param: 1
        desc: 'минута'
        mask: 0b11111111
        shift: 0
        mul: 1
      - name: 'sec'
        type: 'bit_value'
        number: 2
        len_param: 1
        desc: 'секунда'
        mask: 0b11111111
        shift: 0
        mul: 1
  - name: 'mode'
    type: 'value'
    len: 1
    values:
      - name: 'lsm_module_0'
        type: 'bit_value'
        number: 0
        len_param: 1
        desc: 'единицы'
        mask: 0b00000001
        shift: 0
        mul: 1
      - name: 'lsm_module_1'
        type: 'bit_value'
        number: 0
        len_param: 1
        desc: 'единицы'
        mask: 0b00000010
        shift: 1
        mul: 1
      - name: 'lsm_module_2'
        type: 'bit_value'
        number: 0
        len_param: 1
        desc: 'единицы'
        mask: 0b00000100
        shift: 2
        mul: 1
      - name: 'lsm_module_3'
        type: 'bit_value'
        number: 0
        len_param: 1
        desc: 'единицы'
        mask: 0b00001000
        shift: 3
        mul: 1
      - name: 'fotoavtomat'
        type: 'bool_value'
        number: 0
        len_param: 1
        desc: 'фотоавтомат'
        mask: 0b00010000
        shift: 4
        mul: 1
      - name: 'dynamic_power'
        type: 'bool_value'
        number: 0
        len_param: 1
        desc: 'динамическое управление мощностью'
        mask: 0b00100000
        shift: 5
        mul: 1
      - name: 'max_nom_power'
        type: 'bit_value'
        number: 0
        len_param: 1
        desc: 'максимальная мощность (1 - макс. / 0 - номин.)'
        mask: 0b01000000
        shift: 6
        mul: 1           
      - name: 'current_illumination'
        type: 'bit_value'
        number: 0
        len_param: 1
        desc: 'текущая освещенность (1 - день / 0 - ночь.)'
        mask: 0b10000000
        shift: 7
        mul: 1
  - name: 'state_module'
    type: 'value'
    len: 1
    values:
      - name: 'radiation'
        type: 'bool_value'
        number: 0
        len_param: 1
        desc: 'излучение'
        mask: 0b00001000
        shift: 3
        mul: 1
      - name: 'vertical_scan'
        type: 'bool_value'
        number: 0
        len_param: 1
        desc: 'вертикальная развертка'
        mask: 0b00000100
        shift: 2
        mul: 1
      - name: 'horizontal_scan'
        type: 'bool_value'
        number: 0
        len_param: 1
        desc: 'горизонтальная развертка'
        mask: 0b00000010
        shift: 1
        mul: 1
      - name: 'synchronization'
        type: 'bool_value'
        number: 0
        len_param: 1
        desc: 'синхронизация'
        mask: 0b00000001
        shift: 0
        mul: 1
  - name: 'temperature_module'
    type: 'value'
    len: 1
    values:
      - name: 'temperature'
        type: 'sig_value'
        number: 0
        len_param: 1
        desc: 'темпиратура'
        mask: 0b11111111
        shift: 0
        mul: 1 
  - name: 'power_module'
    type: 'value'
    len: 1
    values: 
      - name: 'cur_power'
        type: 'bit_value'
        number: 0
        len_param: 1
        desc: 'текущая мощность в процентах'
        mask: 0b11111111
        shift: 0
        mul: 0.1
  - name: 'U'
    type: 'value'
    len: 1
    values: 
      - name: 'U'
        type: 'bit_value'
        number: 0
        len_param: 1
        desc: 'напряжение'
        mask: 0b11111111
        shift: 0
        mul: 0.1 
  - name: 'I'
    type: 'value'
    len: 1
    values: 
      - name: 'I'
        type: 'bit_value'
        number: 0
        len_param: 1
        desc: 'ток'
        mask: 0b11111111
        shift: 0
        mul: 0.1
  - name: 'T_hull'
    type: 'value'
    len: 1
    values:
      - name: 'temperature_hull'
        type: 'sig_value'
        number: 0
        len_param: 1
        desc: 'темпиратура'
        mask: 0b11111111
        shift: 0
        mul: 1 
  - name: 'T_ODT'
    type: 'value'
    len: 1
    values:
      - name: 'temperature_odt'
        type: 'sig_value'
        number: 0
        len_param: 1
        desc: 'темпиратура'
        mask: 0b11111111
        shift: 0
        mul: 1
  - name: 'heating'
    type: 'value'
    len: 1
    values:
      - name: 'heating_windows_bottom'
        type: 'bool_value'
        number: 0
        len_param: 1
        desc: 'Подогрев иллюминаторов низ'
        mask: 0b00000001
        shift: 0
        mul: 1 
      - name: 'heating_windows_top'
        type: 'bool_value'
        number: 0
        len_param: 1
        desc: 'Подогрев иллюминаторов вверх'
        mask: 0b00000010
        shift: 1
        mul: 1     
      - name: 'heating_lm'
        type: 'bool_value'
        number: 0
        len_param: 1
        desc: 'Подогрев ЛМ'
        mask: 0b00000100
        shift: 2
        mul: 1  
      - name: 'heating_air'
        type: 'bool_value'
        number: 0
        len_param: 1
        desc: 'Подогрев воздуха в корпусе'
        mask: 0b00001000
        shift: 3
        mul: 1 
      - name: 'peltier_minus_1'
        type: 'bool_value'
        number: 0
        len_param: 1
        desc: 'peltier_minus'
        mask: 0b00010000
        shift: 4
        mul: 1 
      - name: 'peltier_plus_1'
        type: 'bool_value'
        number: 0
        len_param: 1
        desc: 'peltier_plus'
        mask: 0b00100000
        shift: 5
        mul: 1    
      - name: 'peltier_minus_2'
        type: 'bool_value'
        number: 0
        len_param: 1
        desc: 'peltier_minus'
        mask: 0b01000000
        shift: 6
        mul: 1 
      - name: 'peltier_plus_2'
        type: 'bool_value'
        number: 0
        len_param: 1
        desc: 'peltier_plus'
        mask: 0b10000000
        shift: 7
        mul: 1 
  - name: 'cooling'
    type: 'value'
    len: 1
    values:
      - name: 'cooler'
        type: 'bool_value'
        number: 0
        len_param: 1
        desc: 'Вентиляторы'
        mask: 0b00000001
        shift: 0
        mul: 1 
  - name: 'state_event'
    type: 'value'
    len: 1
    values: 
      - name: 'synchronization_modules'
        type: 'bit_value'
        number: 0
        len_param: 1
        desc: 'синхронизация между модулями'
        mask: 0b11110000
        shift: 4
        mul: 1
      - name: 'source_history'
        type: 'bit_value'
        number: 0
        len_param: 1
        desc: 'источник события'
        mask: 0b00001111
        shift: 0
        mul: 1