
commands: 
  - name: 'link_request'
    desc: 'Запрос канала связи'
    query: '00'
    response: '80'
  - name: 'short_status'
    desc: 'Запрос текущего краткого состояния ЛСМ'
    query: '01'
    response: '81'
  - name: 'general_status'
    desc: 'Запрос текущего общего состояния ЛСМ'
    query: '02'
    response: '82'
  - name: 'full_status'
    desc: 'Запрос текущего полного состояния ЛСМ '
    query: '03'
    response: '83'
  - name: 'set_setting'
    desc: 'Команда установки режима работы ЛСМ'
    query: '04'
    response: '84'
  - name: 'reset_setting'
    desc: 'Команда перезагрузки ЛСМ'
    query: '05'
    response: '85'
  - name: 'set_factory_setting'
    desc: 'Команда сброса ЛСМ в заводские настройки'
    query: '06'
    response: '86'
  - name: 'stop'
    desc: 'Команда остановки ЛСМ («СТОП ЛСМ»)'
    query: '07'
    response: '87'
  - name: 'start'
    desc: 'Команда пуска ЛСМ («ПУСК ЛСМ»)'
    query: '08'
    response: '88'
  - name: 'save_setting'
    desc: 'Сохранение текущих настроек ЛСМ'
    query: '09'
    response: '89'
  - name: 'current_time'
    desc: 'Запрос текущего времени'
    query: '0A'
    response: '8A'
  - name: 'set_time'
    desc: 'Команда установки времени'
    query: '0B'
    response: '8B'
  - name: 'last_event'
    desc: 'Запрос номера последнего события'
    query: '0C'
    response: '8C'
  - name: 'number_event'
    desc: 'Запрос данных из памяти событий'
    query: '0D'
    response: '8D'
  - name: 'delete_event_memory'
    desc: 'Стирание данных из памяти событий'
    query: '0E'
    response: '8E'
  - name: 'address_book'
    desc: 'Запрос адресной книги'
    query: '0F'
    response: '8F'
  - name: 'write_to_address_book'
    desc: 'Команда записи в адресную книгу'
    query: '10'
    response: '90'
  - name: 'get_max_power'
    desc: 'Запрос текущей максимальной мощности'
    query: '11'
    response: '91'
  - name: 'set_max_power'
    desc: 'Команда установки максимальной мощности'
    query: '12'
    response: '92'
  - name: 'vertical_correction_request'
    desc: 'Запрос коррекции вертикальной развертки'
    query: '13'
    response: '93'
  - name: 'set_vertical_correction'
    desc: 'Команда коррекции вертикальной развертки'
    query: '14'
    response: '94'
  - name: 'horizontal_correction_request'
    desc: 'Запрос коррекции горизонтальной развертки'
    query: '15'
    response: '95'
  - name: 'set_horizontal_correction'
    desc: 'Команда коррекции горизонтальной развертки'
    query: '16'
    response: '96'
  - name: 'test'
    desc: 'Команда включения тестового режима («ТЕСТ»)'
    query: '17'
    response: '97'
  - name:  'event_of_change'
    desc: 'Сообщение об изменении состояния и режима'
    query: '18'
    response: '98'

